project:
  name: hrms

gateway_service:
  enabled: true
  namespace: istio-gateway
  name: auth-gateway
  hostname: "hrms.anasolconsultancyservices.com"
  isthio_injection: "disable"
  listeners:
    - name: hrms-http-listener
      hostname: "hrms.anasolconsultancyservices.com"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: hrms-https-listener
      hostname: "hrms.anasolconsultancyservices.com"
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - kind: Secret
            name: cirtificate-hrms-secret
      allowedRoutes:
        namespaces:
          from: All
    - name: postgress-listener
      port: 5432
      protocol: TCP
      allowedRoutes:
        namespaces:
          from: All
    - name: redis-listener
      port: 5432
      protocol: TCP
      allowedRoutes:
        namespaces:
          from: All
certificate:
  enabled: false
  name: certificate-hrms
  secretName: cirtificate-hrms-secret
  dnsNames:
    - "*.anasolconsultancyservices.com"
  email: chinnollakoteshwar@gmail.com
  issuer:
    name: letsencrypt
    kind: ClusterIssuer
    server: https://acme-v02.api.letsencrypt.org/directory
  route53:
    region: us-east-1
    secretName: route53-secret
    accessKeyIdKey: access-key-id
    secretAccessKeyKey: secret-access-key