apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway_service.name }}
  namespace: {{ .Values.gateway_service.namespace }}
  labels:
    istio-injection: {{ .Values.gateway_service.isthio_injection | default "disable" }}
spec:
  gatewayClassName: istio
  listeners:
  {{- range .Values.gateway_service.listeners }}
  - name: {{ .name }}
    {{- if .hostname }}
    hostname: {{ .hostname | quote }}
    {{- end }}
    port: {{ .port }}
    protocol: {{ .protocol }}
    {{- if .tls }}
    tls:
      certificateRefs:
        {{- range .tls.certificateRefs }}
        - kind: {{ .kind }}
          name: {{ .name }}
        {{- end }}
    {{- end }}
    allowedRoutes:
      namespaces:
        from: {{ .allowedRoutes.namespaces.from }}
  {{- end }}
